Us04
fga-eps-mds/2024.1-SENTINELA-FRONT pull request #10
Opened 2024-07-25 02:58 UTC by Gam13

**Issue: 04 closes [Issue 04](https://github.com/fga-eps-mds/2024.1-SENTINELA-DOC/issues/19)

## Descrição
Foram criadas 4 páginas, uma como hub que chamamos de /cadastro, a pasta dela é Registration, desse hub podemos ir pra lista de usuários cadastrados ou criar um novo usuário, na lista de usuários é possível selecionar um usuário para ver os dados dele, editar ou deletar.

2. O modal padrão foi modificado para comportar caixas de diálogos customizáveis e mais de um botão, sendo agora necessário passar os botões na criação do modal

3. O campo de email é necessário ser válido para ser reconhecido

4. O campo de celular só aceita celulares dentro do padrão, utilizando um componente para campos numéricos que precisam de máscara, a mascara é customizável.

5. O campo de nome só aceita letras

6. Os formulários e a lista de usuários estão compatíveis mobile

7.Back-end funcional com front

2024-07-25 14:26 UTC, yukioz requested changes
Bom trabalho pessoal, arrumar esses ajustes pendentes e tá aprovado!

2024-07-25 14:26 UTC, yukioz commented on src/Styles/global.js
> +export default theme;
porque mudaram a forma de exporta o theme? outras duplas podem ter que mudar a forma que importam se isso os afetou de alguma forma. Porem, podem deixar assim não é grande problema

2024-07-25 14:26 UTC, yukioz commented on src/Routes/protectedRoutes.jsx
> +              </Routes>
o nome dos endereços das páginas podem melhorar. sugestão:

<Route path ="/cadastrarUsuario" element={<Register_User/>}/>
<Route path = "/usuarios/:id" element={<Viewuser/>}/>
<Route path="/usuarios" element={<ListUser/>}/>
<Route path= "/usuarios/cadastros" element = {<Registrations/>} />

2024-07-25 14:26 UTC, yukioz commented on src/Pages/Protected/Listuser/index.jsx
> +    };
Aqui está a maior alteração. vocês estão dando navigate para:

navigate('/usuario', { state: { userId: user._id } });

o correto seria:

navigate('/usuario/${userID}', { state: { userId: user._id } });


Você podem mantar a mesma lógica para capturar o id do usuário, mas outra opção seria buscar o "id" nos parametro da URl usando, exemplo:

URL: "minhapagina.com/usuario/31798712837"

 const { id } = useParams();
 
 useEffect(() => {
    setUserId(id);
  }, [id]);

2024-07-26 03:11 UTC, Gam13 commented on src/Styles/global.js
> +export default theme;
Essa mudança foi feita na us de outra pessoa, quando demos merge para pegar alguns componentes ela veio junta

2024-07-27 02:37 UTC, yukioz commented
LGTM!

2024-07-27 02:38 UTC, yukioz approved these changes
mt bom

2024-07-29 04:25 UTC, merged